# Generated by Django 3.2.8 on 2021-11-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_donor_patient',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]