# Generated by Django 3.0.5 on 2021-11-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbb', '0002_alter_reg_donor_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_donor_patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]