# Generated by Django 3.2.8 on 2021-12-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbb', '0006_alter_add_reqblood_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_reqdonate',
            name='status',
            field=models.CharField(choices=[('Request Sent', 'Request Sent'), ('Pending', 'Pending'), ('Reject', 'Reject'), ('Approved', 'Approved')], max_length=20, null=True),
        ),
    ]
