# Generated by Django 3.2.8 on 2021-12-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbb', '0007_alter_add_reqdonate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_reqdonate',
            name='unit',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
