# Generated by Django 3.2.3 on 2022-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbb', '0008_alter_add_reqdonate_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apos', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Aneg', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Bpos', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Bneg', models.DecimalField(decimal_places=0, max_digits=9)),
                ('ABpos', models.DecimalField(decimal_places=0, max_digits=9)),
                ('ABneg', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Opos', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Oneg', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='reg_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('Medical Technologist', 'Medical Technologist'), ('Physician', 'Physician'), ('Nurse', 'Nurse')], max_length=30)),
                ('sex', models.CharField(max_length=6)),
                ('contactnum', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
    ]
