# Generated by Django 3.2.8 on 2021-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('Medical Technologist', 'Medical Technologist'), ('Physician', 'Physician'), ('Nurse', 'Nurse')], max_length=30)),
                ('sex', models.DecimalField(decimal_places=0, max_digits=3)),
                ('contactnum', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
    ]
