# Generated by Django 3.2.8 on 2021-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_admin',
            name='sex',
            field=models.CharField(max_length=6),
        ),
    ]
