# Generated by Django 3.2.8 on 2021-12-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbb', '0002_alter_reg_admin_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apos', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Aneg', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Bpos', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Bneg', models.DecimalField(decimal_places=0, max_digits=9)),
                ('ABpos', models.DecimalField(decimal_places=0, max_digits=9)),
                ('ABneg', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Opos', models.DecimalField(decimal_places=0, max_digits=9)),
                ('Oneg', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
    ]
